name: Portfolio_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+4
  provider: ^6.0.3
  http: ^1.2.1
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.5.0
  icons_plus: ^5.0.0
  get: ^4.6.6
  dio: ^5.4.2+1
  google_fonts: ^6.2.1
  flutter_map: ^7.0.1
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.7.0
  carousel_slider: ^4.1.1
  flutter_secure_storage: ^9.2.2
  loading_animation_widget: ^1.2.1
  connectivity_plus: ^3.0.3
  filter_list: ^1.0.3
  curved_navigation_bar: ^1.0.6
  latlong2: ^0.9.1
  geolocator: ^8.2.0
  path: ^1.8.0
  path_provider: ^2.1.3
  liquid_swipe: ^3.1.0
  flutter_svg: ^2.0.10+1
  flare_flutter: ^3.0.2
  haptic_feedback: ^0.5.1+1
  flutter_zoom_drawer: ^3.2.0
  awesome_notifications: ^0.9.3+1
  cached_network_image: ^3.3.1
  getwidget: ^4.0.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  intl: any
  intl_utils: ^2.8.7
  flutter_localization: ^0.2.0
  dots_indicator: ^3.0.0
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
